/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { OwnableContract } from "./Ownable";
import { ERC20Contract } from "./ERC20";
import { ERC20CappedContract } from "./ERC20Capped";
import { IERC20Contract } from "./IERC20";
import { StakingContract } from "./Staking";
import { NUSDContract } from "./NUSD";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Ownable"): OwnableContract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC20Capped"): ERC20CappedContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "Staking"): StakingContract;
      require(name: "NUSD"): NUSDContract;
    }
  }
}

export { OwnableContract, OwnableInstance } from "./Ownable";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { ERC20CappedContract, ERC20CappedInstance } from "./ERC20Capped";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { StakingContract, StakingInstance } from "./Staking";
export { NUSDContract, NUSDInstance } from "./NUSD";
